language: java
jdk: oraclejdk8
os: linux
sudo: false
cache:
  directories:
  - $HOME/.gradle
branches:
  only:
  - dev
  - master
services:
  - mysql
before_install:
  - mysql -e "create database IF NOT EXISTS dimotest;" -uroot
script: gradle clean build
